# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APP-Sound' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APP-Sound
  pod 'EMTNeumorphicView'
  pod 'SwiftySound'
  pod "SwiftSiriWaveformView"
  target 'APP-SoundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APP-SoundUITests' do
    # Pods for testing
  end

end
